version: '3'
services:
  expiry_mysql:
    image: mysql:8.0.33
    container_name: expiry_mysql
    restart: always
    volumes:
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8 --collation-server=utf8_bin
    networks:
      - expiry_network

  expiry_api:
    build:
      context: ./expiry/expiry_api
      dockerfile: Dockerfile
    container_name: expiry_api
    restart: always
    volumes:
      - ./expiry/expiry_api/config/config.ini:/app/config/config.ini
      - ./expiry/expiry_api/log:/app/log
    environment:
      - TZ=Asia/Shanghai
    networks:
      - expiry_network
    depends_on:
      - expiry_mysql

  expiry_alert:
    build:
      context: ./expiry/expiry_alert
      dockerfile: Dockerfile
    container_name: expiry_alert
    restart: always
    volumes:
      - ./expiry/expiry_alert/config/config.ini:/app/config/config.ini
      - ./expiry/expiry_alert/log:/app/log
    environment:
      - TZ=Asia/Shanghai
    networks:
      - expiry_network
    depends_on:
      - expiry_mysql

  expiry_web:
    build:
      context: ./expiry/expiry_web
      dockerfile: Dockerfile
    container_name: expiry_web
    restart: always
    volumes:
      - ./expiry/expiry_web/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - expiry_network
    depends_on:
      - expiry_api

  expiry_nginx:
    image: nginx:1.25.1
    container_name: expiry_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - expiry_network
    depends_on:
      - expiry_web

networks:
  expiry_network:
    driver: bridge
